# Generated by Django 5.2.3 on 2025-08-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tips/')),
                ('category', models.CharField(choices=[('soil', 'Soil & Nutrients'), ('watering', 'Watering & Irrigation'), ('pest', 'Pest & Disease'), ('harvest', 'Harvest & Storage'), ('general', 'General')], default='general', max_length=32)),
                ('crop', models.CharField(blank=True, help_text='Optional crop name for filtering', max_length=100)),
                ('season', models.CharField(blank=True, help_text='Optional season for filtering', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
